### ISSUE TITLE
`blob.tags` results in a runtime error: `RuntimeError: generator raised StopIteration`

### ISSUE THREAD

**Issue by SamEdwardes** [sloria/textblob-fr#10]
When I attempt to access the `.tags` attribute I get a `RuntimeError: generator raised StopIteration`. This may be related to PR #9.

```python
from textblob import TextBlob
from textblob_fr import PatternTagger, PatternAnalyzer
text = u"Quelle belle matinée"
blob = TextBlob(text, pos_tagger=PatternTagger(), analyzer=PatternAnalyzer())
print(blob.sentiment)
# (0.8, 0.8)
print(blob.tags)
```

```python
Traceback (most recent call last):
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 351, in _read
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/samedwardes/git/spacytextblob/textblob-fr-example.py", line 6, in <module>
    print(blob.tags)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob/decorators.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob/blob.py", line 484, in pos_tags
    return [val for sublist in [s.pos_tags for s in self.sentences] for val in sublist]
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob/blob.py", line 484, in <listcomp>
    return [val for sublist in [s.pos_tags for s in self.sentences] for val in sublist]
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob/decorators.py", line 24, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob/blob.py", line 487, in pos_tags
    for word, t in self.pos_tagger.tag(self)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/taggers.py", line 17, in tag
    return pattern_tag(sentence, tokenize)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/fr.py", line 217, in tag
    for sentence in parse(s, tokenize, True, False, False, False, encoding).split():
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/fr.py", line 201, in parse
    return parser.parse(s, *args, **kwargs)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 1596, in parse
    s[i] = self.find_tags(s[i], **kwargs)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/fr.py", line 150, in find_tags
    return _Parser.find_tags(self, tokens, **kwargs)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 1540, in find_tags
    return find_tags(tokens,
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 1350, in find_tags
    tagged.append([token, lexicon.get(token, i==0 and lexicon.get(token.lower()) or None)])
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 98, in get
    return self._lazy("get", *args)
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 79, in _lazy
    self.load()
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 367, in load
    dict.update(self, (x.split(" ")[:2] for x in _read(self._path) if x.strip()))
  File "/Users/samedwardes/Library/Caches/pypoetry/virtualenvs/spacytextblob-u83tqr8m-py3.9/lib/python3.9/site-packages/textblob_fr/_text.py", line 367, in <genexpr>
    dict.update(self, (x.split(" ")[:2] for x in _read(self._path) if x.strip()))
RuntimeError: generator raised StopIteration
```

System information:

- Mac OS
- Python 3.9.4

```bash
❯ pip list
Package                        Version
------------------------------ ---------
appdirs                        1.4.4
appnope                        0.1.2
argon2-cffi                    20.1.0
async-generator                1.10
attrs                          20.3.0
backcall                       0.2.0
black                          20.8b1
bleach                         3.3.0
blis                           0.7.4
catalogue                      2.0.1
certifi                        2020.12.5
cffi                           1.14.5
chardet                        4.0.0
click                          7.1.2
cymem                          2.0.5
decorator                      5.0.3
defusedxml                     0.7.1
en-core-web-sm                 3.0.0
entrypoints                    0.3
ghp-import                     2.0.2
idna                           2.10
importlib-metadata             4.8.3
iniconfig                      1.1.1
ipykernel                      5.5.3
ipython                        7.16.1
ipython-genutils               0.2.0
jedi                           0.18.0
Jinja2                         2.11.3
joblib                         1.0.1
json5                          0.9.5
jsonschema                     3.2.0
jupyter-client                 6.1.12
jupyter-core                   4.7.1
jupyterlab                     2.3.1
jupyterlab-pygments            0.1.2
jupyterlab-server              1.2.0
Markdown                       3.3.6
MarkupSafe                     1.1.1
mergedeep                      1.3.4
mistune                        0.8.4
mkdocs                         1.2.3
mkdocs-include-markdown-plugin 3.2.3
mkdocs-material                8.1.11
mkdocs-material-extensions     1.0.3
murmurhash                     1.0.5
mypy-extensions                0.4.3
nbclient                       0.5.1
nbconvert                      6.0.7
nbformat                       5.1.3
nest-asyncio                   1.5.1
nltk                           3.5
notebook                       6.3.0
numpy                          1.19.5
packaging                      20.9
pandocfilters                  1.4.3
parso                          0.8.2
pathspec                       0.8.1
pathy                          0.4.0
pexpect                        4.8.0
pickleshare                    0.7.5
pip                            21.3.1
pluggy                         0.13.1
preshed                        3.0.5
prometheus-client              0.10.0
prompt-toolkit                 3.0.3
ptyprocess                     0.7.0
py                             1.10.0
pycparser                      2.20
pydantic                       1.7.3
Pygments                       2.11.2
pymdown-extensions             9.1
pyparsing                      2.4.7
pyrsistent                     0.17.3
pytest                         6.2.2
python-dateutil                2.8.1
PyYAML                         6.0
pyyaml_env_tag                 0.1
pyzmq                          22.0.3
regex                          2021.3.17
requests                       2.25.1
Send2Trash                     1.5.0
setuptools                     58.3.0
six                            1.15.0
smart-open                     3.0.0
spacy                          3.0.5
spacy-legacy                   3.0.2
spacytextblob                  3.1.0
srsly                          2.4.0
terminado                      0.9.4
testpath                       0.4.4
textblob                       0.15.3
textblob-fr                    0.2.0
thinc                          8.0.2
toml                           0.10.2
tornado                        6.1
tqdm                           4.59.0
traitlets                      4.3.3
typed-ast                      1.4.2
typer                          0.3.2
typing-extensions              3.7.4.3
urllib3                        1.26.4
wasabi                         0.8.2
watchdog                       2.1.6
wcwidth                        0.2.5
webencodings                   0.5.1
wheel                          0.37.0
zipp                           3.4.1
```

**Comment by gmat** [comment]
same bug on linux with python 3.11.3 (I should test with 3.8.x)

**Comment by gmat** [comment]
> same bug on linux with python 3.11.3 (I should test with 3.8.x)

I didn't test python 3.9 I just saw the PR #9 mentions upper and I test it. Works great :+1:
